name: "Bug"
description: "Relate um problema"
labels: ["bug"]
body:
  - type: textarea
    id: current
    attributes:
      label: O que aconteceu?
      placeholder: "Explique o comportamento atual, erro ou impacto."
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Como reproduzir?
      placeholder: |
        1. Acesse...
        2. Clique em...
        3. Veja o erro...

  - type: textarea
    id: expected
    attributes:
      label: O que era esperado?
      placeholder: "O que deveria acontecer?"

  - type: textarea
    id: context
    attributes:
      label: Evidencias
      placeholder: "Logs, prints, ambiente, navegador ou links."
