name: "Documentacao"
description: "Sugira criacao ou ajuste de documentacao"
labels: ["documentation"]
body:
  - type: textarea
    id: location
    attributes:
      label: Onde
      placeholder: "README, docs, comentario no codigo, issue relacionada..."

  - type: textarea
    id: context
    attributes:
      label: Contexto
      placeholder: "Links, exemplos ou observacoes."
