name: "Documentação"
description: "Sugira ajuste de documentação"
labels: ["documentation"]
body:
  - type: textarea
    id: location
    attributes:
      label: Onde
      placeholder: "README, docs, comentário no código, rota, componente..."
    validations:
      required: true

  - type: textarea
    id: change
    attributes:
      label: O que ajustar?
      placeholder: "O que falta, está confuso ou precisa ser atualizado?"
    validations:
      required: true
