name: "Funcionalidade"
description: "Sugira uma melhoria ou nova funcionalidade"
labels: ["enhancement"]
body:
  - type: textarea
    id: context
    attributes:
      label: Contexto
      placeholder: "Links, referencias, prints ou observacoes."
